### PR TITLE
Renable assertion

### LINKED ISSUE #29: Possible to hit assertion failure in malleability check
Adding this to the `roundtrip_descriptor` fuzztest resuls in a panic:
```
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test() {
        do_test(b"eltr(hbs0k_eqns(h1ror_tr(rmNnelt,is_p_spk1los_and_4wsh085oh562inp_is-279sue_v5nl:thresh(1,spk_eq(,88707488)))");
    }   
}
```
This looks like it's a real bug, not a fuzzer artifact, though I haven't investigated yet
```
assertion failed: self.mall.non_malleable || self.corr.input != Input::Zero', /store/home/apoelstra/code/ElementsProject/elements-miniscript/fuzzing/src/miniscript/types/mod.rs:556:9
```

### PR DESCRIPTION
**Pull request by sanket1729**
Rethink about correctness/malleability properites in covenants. See the commit description

### CODE REVIEW

**Comment by apoelstra** [comment]
Ooo, very interesting CI failure
```
thread 'descriptor::csfs_cov::tests::parse_cov' panicked at 'called `Result::unwrap()` on an `Err` value: TypeCheck("fragment «thresh(2,ver_eq(1),s:pk(C),s:pk(B))» sub-fragment 0 can not be dissatisfied and cannot be used in a threshold")', src/descriptor/csfs_cov/mod.rs:86:61
```
I think this is, strictly speaking, true, and we cannot sensibly/correctly use a threshold of covenant conditions! Miniscript saves us again.

**Comment by apoelstra** [comment]
This looks good, though I realize I was confused -- I thought all the covenant fragments were `VERIFY` conditions and actually couldn't be dissatisfied even by modifying the transaction.

But they're not so, the situation is more subtle...
* Any introspection of the current input cannot be dissatisfied under any circumstances, without changing the input (but then we're executing a totally different miniscript :))
* Any introspection of other inputs, or outputs, *can* be dissatisfied but are only malleable if the relevant data is unsigned (i.e. the fragment is non-`safe`). IOW the assertion is actually wrong and you were initially correct to remove it.
* It is actually totally fine to have a threshold of covenant fragments

Having said that, I'm a bit scared to remove this assertion because it reflects an underlying assumption about Miniscript that we're eliminating...I wonder if we **should** make all the covenant requirements verify-only and force the user to use a `d:` wrapper? But then we're forcing inefficiency.

**Review by apoelstra — APPROVED** [review]
ACK 61c2f3a6cfb8217695064aee67f791a98b950b27

**Comment by sanket1729** [comment]
> I wonder if we should make all the covenant requirements verify-only and force the user to use a d: wrapper?

This is what I am leaning towards.

**Comment by apoelstra** [comment]
Cool. It would be fine for us to later expand the language if it turned out that we need non-`VERIFY` covenants in a lot of contexts, so if `VERIFY`-only lets us simplify our reasoning, let's do that for now.

**Comment by sanket1729** [comment]
> I'm a bit scared to remove this assertion because it reflects an underlying assumption about Miniscript that we're eliminating..

The assertion is re-enabled in this PR.

> I wonder if we should make all the covenant requirements verify-only and force the user to use a d: wrapper?

Upon more investigation, there is some work in changing the miniscripts as it would require editing all the tests. IMO, the current fix with assertion enabled should be fine for now.

**Pull request merged**
