### PR TITLE
Add IndexOps Spec

### PR DESCRIPTION
**Pull request by sanket1729**
Allows more flexible covenant creation. Required for Limit orders implementation. 

This will allow many more covenants to be expressed in `elements-miniscript`. I think this makes us feature complete for the time being :crossed_fingers:  . At the very least, I cannot think of us needing any extensions that we are missing

### CODE REVIEW

**Comment by apoelstra** [comment]
e0871e646635701cceddf2f4796595d6cf978be8 looks great -- but do we need to use 64-bit addition for index ops? Seems like we could use the old-school 32-bit addition opcode.

**Comment by sanket1729** [comment]
We don't need it, I just used it for consistency with other opcodes.

**Comment by apoelstra** [comment]
I think we should drop it, and require that index expressions lie between 0 and 2^31-1. (Or is it 2^32 - 1? I don't recall, but it doesn't matter :)).

**Comment by sanket1729** [comment]
Updated with the requested suggestions.

**Comment by apoelstra** [comment]
Ok, LGTM. I am tempted to say that indices should be bounded below by 0, not 2^31 - 1, because conceptually indices are nonnegative. But I could imagine this being annoying in certain cases where it would impose order-of-operations requirements on arithmetic. And also it would require extra opcodes to enforce this.

Will ACK shortly.

**Review by apoelstra — APPROVED** [review]
ACK 75f06818ccea3bb953545869fa0a82a8a8a73ec3

**Comment by apoelstra** [comment]
We should probably also update the README to indicate the new `cargo update -p` requirement.

**Comment by sanket1729** [comment]
@apoelstra, done in #40

**Pull request merged**
