### PR TITLE
elip151: concatenate unprefixed opcode and script pubkey

### PR DESCRIPTION
**Pull request by LeoComandini**
This is a breaking change but it adheres more to the ELIP.

### CODE REVIEW

**Comment by LeoComandini** [comment]
Currently for scriptpubkey `0014aa..aa`, we hash `01ff160014aa...aa`
After this we hash `ff0014aa..aa`

Not sure what's the appropriate thing to do here,
we can go with this MR and change the ELIP test vectors,
we can serialize in a different way,
or edit the ELIP to match the implementation.

**Comment by apoelstra** [comment]
Agreed this is better. Though would be very easy to change the ELIP to say "you have to encode 01ff" rather than "you have to encode ff".

I guess, the question is, is this used anywhere and what would be the consequence of breaking it?

**Comment by LeoComandini** [comment]
> is this used anywhere and what would be the consequence of breaking it?

It is exposed by lwk but I've no evidence of anyone using this in prod.
So in theory we're in time to change this if we prefer.

**Comment by apoelstra** [comment]
I have no preference **and** I'm not involved with lwk at all. So you need to make the call (or find somebody who will).

Just let me know.

**Comment by LeoComandini** [comment]
@apoelstra 
I think minimal disruption is changing the ELIP, 
opened https://github.com/ElementsProject/ELIPs/pull/13
I'll close this once that is merged

**Comment by LeoComandini** [comment]
We chose to amend the ELIP, closing

**Pull request closed without merging**
