### PR TITLE
Merge may 2022

### PR DESCRIPTION
**Pull request by sanket1729**
The merge commits have a short description for each PR. 2-3 PRs were not merged because they were refactors related to Translation methods that would be overhauled shortly.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
utACK 02b04c105013f884f813da1b6e08ca7c20c84439

I ran `git show` on every merge commit and at least looked at it, though many showed large diffs since `git show` handles merge conflicts really poorly. I reviewed all the non-merge commits, which were basically entirely formatting and clippy.

I also glanced at the total diff between upstream 104eb55 and this PR, but the diff is still much too large to review by hand.

This all looks good to me.

**Comment by apoelstra** [comment]
Looks like we need one more commit to fix CI.

**Comment by apoelstra** [comment]
utACK 62c0234e8437edd1a9f5844cd6d24f9f06ffd2e4

**Comment by sanket1729** [comment]
Fixed the CI and merged.

**Pull request merged**
